-- MySQL Script generated by MySQL Workbench
-- Sat 16 Jun 2018 07:45:57 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Local` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `idLocal` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Regiao` VARCHAR(45) NOT NULL,
  `EstatisticaPartidaria` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coligacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coligacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coligacao` (
  `idColigacao` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Majoritaria` TINYINT(1) NOT NULL,
  `Proporcional` TINYINT(1) NOT NULL,
  `Presidente` INT NOT NULL,
  PRIMARY KEY (`idColigacao`),
  UNIQUE INDEX `Presidente_UNIQUE` (`Presidente` ASC),
  CONSTRAINT `fk_Presidente`
    FOREIGN KEY (`Presidente`)
    REFERENCES `mydb`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partido` (
  `idPartido` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(10) NOT NULL,
  `Alinhamento` VARCHAR(45) NULL,
  `Coligacao_idColigacao` INT NOT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `fk_Partido_Coligação1_idx` (`Coligacao_idColigacao` ASC),
  CONSTRAINT `fk_Partido_Coligação1`
    FOREIGN KEY (`Coligacao_idColigacao`)
    REFERENCES `mydb`.`Coligacao` (`idColigacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Candidato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Candidato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Candidato` (
  `idCandidato` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Foto` BLOB NULL,
  `Formacao` VARCHAR(45) NOT NULL,
  `Propostas` LONGTEXT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  `Partido_idPartido` INT NOT NULL,
  PRIMARY KEY (`idCandidato`),
  INDEX `fk_Candidato_Local1_idx` (`Local_idLocal` ASC),
  INDEX `fk_Candidato_Partido1_idx` (`Partido_idPartido` ASC),
  CONSTRAINT `fk_Candidato_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_Partido1`
    FOREIGN KEY (`Partido_idPartido`)
    REFERENCES `mydb`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Candidatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Candidatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Candidatura` (
  `idCandidatura` INT NOT NULL,
  `IntencaoDeVotos` INT NOT NULL,
  `Candidato_idCandidato` INT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idCandidatura`),
  INDEX `fk_Candidatura_Candidato_idx` (`Candidato_idCandidato` ASC),
  INDEX `fk_Candidatura_Local1_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_Candidatura_Candidato`
    FOREIGN KEY (`Candidato_idCandidato`)
    REFERENCES `mydb`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidatura_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Poder` VARCHAR(45) NOT NULL,
  `PreRequisitos` VARCHAR(45) NULL,
  `Candidatura_idCandidatura` INT NOT NULL,
  PRIMARY KEY (`idCargo`),
  INDEX `fk_Cargo_Candidatura1_idx` (`Candidatura_idCandidatura` ASC),
  CONSTRAINT `fk_Cargo_Candidatura1`
    FOREIGN KEY (`Candidatura_idCandidatura`)
    REFERENCES `mydb`.`Candidatura` (`idCandidatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
